### ISSUE TITLE
Nested collections dumped in flow style

### ISSUE THREAD

**Issue by sanyer** [awslabs/aws-cfn-template-flip#1]
First of all, thank you very much for making this happen. I was very close to starting my own project, but created only a bunch of tests based on my own CF JSON->YAML experience.

Anyway, back to issue.

As of now, cfn-flip dumps nested collections in flow instead of block style.
Would be nice to make it dump in block style.

**Expected result:**
```yaml
Statement:
- Effect: Allow
  Action:
  - s3:AbortMultipartUpload
  - s3:CopyObject
  - s3:DeleteObject
  - s3:DeleteObjectVersion
  - s3:GetLifecycleConfiguration
  - s3:GetObject
  - s3:GetObjectAccessControlPolicy
  - s3:GetObjectAcl
  - s3:GetObjectExtended
  - s3:GetObjectVersion
  - s3:GetObjectVersionAcl
  - s3:ListBucket
  - s3:ListBucketMultipartUploads
  - s3:ListBucketVersions
  - s3:ListMultipartUploadParts
  - s3:PutLifecycleConfiguration
  - s3:PutObject
  - s3:PutObjectAcl
  - s3:PutObjectInline
  - s3:PutObjectVersionAcl
  - s3:SetObjectAccessControlPolicy
```

**Actual result:**
```yaml
Statement:
- Effect: Allow
  Action: ['s3:AbortMultipartUpload', 's3:CopyObject', 's3:DeleteObject',
    's3:DeleteObjectVersion', 's3:GetLifecycleConfiguration', 's3:GetObject',
    's3:GetObjectAccessControlPolicy', 's3:GetObjectAcl', 's3:GetObjectExtended',
    's3:GetObjectVersion', 's3:GetObjectVersionAcl', 's3:ListBucket', 's3:ListBucketMultipartUploads',
    's3:ListBucketVersions', 's3:ListMultipartUploadParts', 's3:PutLifecycleConfiguration',
    's3:PutObject', 's3:PutObjectAcl', 's3:PutObjectInline', 's3:PutObjectVersionAcl',
    's3:SetObjectAccessControlPolicy']
```

Might be done by setting the parameter **default_flow_style** of **yaml.dump()** to **False** (ref: [Dictionaries without nested collections are not dumped correctly](http://pyyaml.org/wiki/PyYAMLDocumentation#Dictionarieswithoutnestedcollectionsarenotdumpedcorrectly))
