### ISSUE TITLE
Cfn flip does not respect parameter types when loading a template

### ISSUE THREAD

**Issue by LucasTaves** [awslabs/aws-cfn-template-flip#104]
Assume the following entry is a parameter in the template:

```
  EngineVersionCompatibility:
    Type: String
    Default: 5.0.4
    AllowedValues:
      - 5.0.4
      - 5.0
      - 5.00
```

When loading it cfn_flip will properly recognize 5.0.4 as a string value. but it will parse both 5.0 and 5.00 to float. Seems a harmless change, but if afterwards you dump the template back as a string those values would both be represented as the '5' string preventing the template to be applied with the expected value of '5.0'

I can get around that by checking all properties that has a Type string and a value that is not string, but differentiating 5.0 from 5.00 becomes tricky unless I parse the whole template on my own.
