### ISSUE TITLE
Cfn-flip fails to parse YAMLs when there is a tab character

### ISSUE THREAD

**Issue by JoseRolles** [awslabs/aws-cfn-template-flip#117]
This doesn't work:
```
Parameters:
  Test:
    Type: String
    Default: Tab here ->	<- tab here
Resources:
  S3:
    Type: AWS::Logs::LogGroup
```

This works:
```
Parameters:
  Test:
    Type: String
    Default: "Tab here ->\t<- tab here"
Resources:
  S3:
    Type: AWS::Logs::LogGroup
```

When using [AWS CloudFormation Designer](https://console.aws.amazon.com/cloudformation/designer/home), somehow it still validates without issue.
