### ISSUE TITLE
Cfn-flip failed to parse YAML with <<

### ISSUE THREAD

**Issue by yuyangd** [awslabs/aws-cfn-template-flip#118]
### Use "<<" to reuse YAML block is supported in CloudFormation

```
---
AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  page: &PAGE_PATH
    AllowedMethods: ['GET', 'HEAD']
    TargetOriginId: 'my-origin'

Resources:
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - PathPattern: '/'
            <<: *PAGE_PATH

```

However, cfn-flip cannot parse "<<".

```
Error: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "<unicode string>", line 17, column 13:
                <<: *PAGE_PATH
                ^
```

### Reason to use "<<"

the final template should show as below

```
 - PathPattern: '/'
    AllowedMethods: ['GET', 'HEAD']
    TargetOriginId: 'my-origin'
```
