### ISSUE TITLE
Multi-level Fn::GetAtt JSON-to-YAML conversion broken

### ISSUE THREAD

**Issue by smphhh** [awslabs/aws-cfn-template-flip#23]
With the following test.json
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Resources": {
        "TestBucket": {
            "Type": "AWS::S3::Bucket",
            "Properties": {
                "BucketName": {
                    "Fn::GetAtt": [
                        "TestDatabase",
                        "Endpoint",
                        "Address"
                    ]
                }
            }
        }
    }
}
```
running
```
cfn-flip test.json
```
yields
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !GetAtt 'TestDatabase.Endpoint'
```
i.e. the ".Address" part is lost. This was working in 0.2.1.
