### ISSUE TITLE
Could not determine the input format. Perhaps it's malformed?

### ISSUE THREAD

**Issue by gilsonm** [awslabs/aws-cfn-template-flip#5]
I get the above error on most of my cloudformation yaml templates. 
These templates are not malformed, in the sense that CloudFormation will parse and launch them as a stack.

What gives?

Here's an example template with some literals redacted.

```
---
AWSTemplateFormatVersion: 2010-09-09
Description: Template for creating Eden.Garden Worker Cluster

Resources:

  Garden:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - 'us-east-1a'
      VPCZoneIdentifier:
        - 'XXXXXXXXXXXX'
      LaunchConfigurationName:
        Ref: WorkerConfig
      MinSize:
        Ref: NumWorkers
      MaxSize:
        Ref: NumWorkers
      Tags:
        - Key: Name
          Value: 'Garden Worker'
          PropagateAtLaunch: 'true'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
        Count:
          Ref: NumWorkers

  WorkerConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: S3
          roleName:
            Ref: WorkerInstanceRole
      AWS::CloudFormation::Init:
        configSets:
          garden_worker_bootstrap:
          - install_ansible
          - download_ansible_bootstrap
          - run_ansible_bootstrap
        install_ansible:
          commands:
            01_pip_install_ansible:
              command:
                Fn::Join:
                - ' '
                - - "pip"
                  - "install"
                  - "ansible"
              cwd: '/home/ec2-user/'
              ignoreErrors: 'false'
        download_ansible_bootstrap:
          files:
            "/home/ec2-user/.eden/bootstrap/worker.bootstrap.yaml":
              source: http://s3.amazonaws.com/xxxxxxxxxxxxxxxxx
              mode: '000744'
              owner: ec2-user
              group: ec2-user
              authentication: S3AccessCreds
              context:
                rabbitmq_host:
                  Ref: RabbitMQHost
                rabbitmq_port:
                  Ref: RabbitMQPort
        run_ansible_bootstrap:
          commands:
            01_run_ansible_bootstrap:
              command:
                Fn::Join:
                - ' '
                - - "/usr/local/bin/ansible-playbook"
                  - "/home/ec2-user/.eden/bootstrap/worker.bootstrap.yaml"
                  - "--connection=local"
              cwd: "/usr/local/bin/"
              ignoreErrors: 'false'
    Properties:
      AssociatePublicIpAddress: 'true'
      KeyName: 'XXXXXX'
      ImageId: XXXXXXXX
      SecurityGroups:
        - Ref: WorkerSecurityGroup
      InstanceType:
        Ref: WorkerInstanceType
      IamInstanceProfile:
        Ref: WorkerInstanceProfile
      BlockDeviceMappings:
        # this is only for AMZ linux, all else use /dev/sda1. Jesus.
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize:
              Ref: WorkerRootVolumeSize
            VolumeType: 'gp2'
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
            - "/opt/aws/bin/cfn-init -v "
            - "         --stack "
            - Ref: AWS::StackName
            - "         --resource WorkerConfig "
            - "         --configsets garden_worker_bootstrap "
            - "         --region "
            - Ref: AWS::Region
            - "\n"
            - "/opt/aws/bin/cfn-signal -e $? "
            - "         --stack "
            - Ref: AWS::StackName
            - "         --resource Garden "
            - "         --region "
            - Ref: AWS::Region
            - "\n"

Parameters:

  NumWorkers:
    Description: Number of workers in the Garden autoscaling group
    Type: String
    Default: 2

  RabbitMQHost:
    Description: DNS name of RabbitMQ server
    Default: 'localhost'
    Type: String

  RabbitMQPort:
    Description: Port of RabbitMQ server
    Default: '5672'
    Type: String

  WorkerInstanceRole:
    Description: Role defining permissions for instances
    Type: String

  WorkerInstanceProfile:
    Description: Profile for instances needing AWS perms
    Type: String

  WorkerSecurityGroup:
    AllowedPattern: 'sg-[a-zA-Z0-9]*'
    ConstraintDescription: must begin with sg- and end with alphanumeric, maybe hex.
    Default: XXXXXXXXXX
    Description: The VPC security group for the RDS instance, specifying ingress rules
    MaxLength: '64'
    MinLength: '4'
    Type: String

  WorkerRootVolumeSize:
    Description: Size in GiB of the worker root volume
    Type: String
    Default: '800'

  WorkerKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: XXXXXX
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  WorkerInstanceType:
    Description: Garden Worker EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.large
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.

Outputs:
  GardenASGName:
    Description: Eden.Garden AutoScaling Group Name
    Value:
      Ref: Garden
```
