### ISSUE TITLE
using clean produces invalid template

### ISSUE THREAD

**Issue by rickalm** [awslabs/aws-cfn-template-flip#63]
we are using `new_template = to_yaml( to_json( orig_template ) )` to cleanup the yaml we are producing with jinja2

`clean_up=False` we see
```
  PublicSubnetIds:
    Description: The public subnetids
    Condition: HasPublicSubnet1AZ1
    Value:
      Fn::Join:
        - ','
        -
          - Fn::If:
            - HasPublicSubnet1AZ1
            - !Ref PublicSubnet1AZ1
            - !Ref AWS::NoValue
          - Fn::If:
            - HasPublicSubnet1AZ2
            - !Ref PublicSubnet1AZ2
            - !Ref AWS::NoValue
          - Fn::If:
            - HasPublicSubnet1AZ3
            - !Ref PublicSubnet1AZ3
            - !Ref AWS::NoValue
    Export:
      Name: !Sub vpc-${Environment}-PublicSubnetIds
```
but with `clean_up=True` we get
```
  PublicSubnetIds:
    Description: The public subnetids
    Condition: HasPublicSubnet1AZ1
    Value: !Sub
      - ${Param1},${Param2},${Param3}
      - Param1: !If
          - HasPublicSubnet1AZ1
          - !Ref 'PublicSubnet1AZ1'
          - !Ref 'AWS::NoValue'
        Param2: !If
          - HasPublicSubnet1AZ2
          - !Ref 'PublicSubnet1AZ2'
          - !Ref 'AWS::NoValue'
        Param3: !If
          - HasPublicSubnet1AZ3
          - !Ref 'PublicSubnet1AZ3'
          - !Ref 'AWS::NoValue'
    Export:
      Name: !Sub 'vpc-${Environment}-PublicSubnetIds'
```
Which CloudFormation complains about .. suggestions ??
