### ISSUE TITLE
Clean  Join replacement can produce invalid template

### ISSUE THREAD

**Issue by christianbeland** [awslabs/aws-cfn-template-flip#69]
it replaces valid template input

```
      Value:
        Fn::Join:
          - ","
          - - Fn::If:
                - HasZoneA
                - Ref: PublicSubnetA
                - Ref: "AWS::NoValue"
            - Fn::If:
                - HasZoneB
                - Ref: PublicSubnetB
                - Ref: "AWS::NoValue"
            - Fn::If:
                - HasZoneC
                - Ref: PublicSubnetC
                - Ref: "AWS::NoValue"
```

by invalid output

```
      Value: !Sub
      - ${Param1},${Param2},${Param3}
      - Param1: !If
          - HasZoneA
          - !Ref 'PublicSubnetA'
          - !Ref 'AWS::NoValue'
        Param2: !If
          - HasZoneB
          - !Ref 'PublicSubnetB'
          - !Ref 'AWS::NoValue'
        Param3: !If
          - HasZoneC
          - !Ref 'PublicSubnetC'
          - !Ref 'AWS::NoValue'
```
      
and then CloudFormation fails with:

> Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string

I temporarily fixed this with the following:

```
import cfn_clean

def clean_without_join_replacement(source: Any) -> Any:
    if isinstance(source, dict):
        for key, value in source.items():
            source[key] = clean_without_join_replacement(value)

    elif isinstance(source, list):
        return [clean_without_join_replacement(item) for item in source]

    return source

cfn_clean.clean = clean_without_join_replacement
```

_Originally posted by @christianbeland in https://github.com/cloudtools/troposphere/issues/976#issuecomment-468007634_
